name: Code Review and Test

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  review-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      statuses: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Review HTML Files
      run: npm run lint:html

    - name: Review CSS Files
      uses: stylelint/actions-stylelint@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review

    - name: Review JS Files
      uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        eslint_flags: "site-js/**/*.js"
